#!/usr/bin/env bash
set -euo pipefail

###############################################################################
# Promise Tracker — Self-Host Setup Script for Proxmox
#
# Prerequisites:
#   - Docker & Docker Compose installed
#   - Ports 8080 (frontend), 8000 (API), 3000 (Studio) available
#
# Usage:
#   chmod +x setup.sh
#   ./setup.sh
###############################################################################

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "============================================"
echo "  Promise Tracker — Self-Host Setup"
echo "============================================"

# ── Step 1: Generate .env if it doesn't exist ──────────
if [ ! -f .env ]; then
  echo ""
  echo "[1/5] Generating .env from template..."

  # Generate secrets
  POSTGRES_PASSWORD=$(openssl rand -hex 24)
  JWT_SECRET=$(openssl rand -hex 32)

  # Generate Supabase JWT keys
  # Anon key (role: anon)
  ANON_KEY=$(python3 -c "
import json, base64, hmac, hashlib, time
header = base64.urlsafe_b64encode(json.dumps({'alg':'HS256','typ':'JWT'}).encode()).rstrip(b'=').decode()
payload_data = {'role':'anon','iss':'supabase','iat':$(date +%s),'exp':$(($(date +%s) + 315360000))}
payload = base64.urlsafe_b64encode(json.dumps(payload_data).encode()).rstrip(b'=').decode()
sig = base64.urlsafe_b64encode(hmac.new('${JWT_SECRET}'.encode(), f'{header}.{payload}'.encode(), hashlib.sha256).digest()).rstrip(b'=').decode()
print(f'{header}.{payload}.{sig}')
" 2>/dev/null || echo "GENERATE_ME")

  SERVICE_ROLE_KEY=$(python3 -c "
import json, base64, hmac, hashlib, time
header = base64.urlsafe_b64encode(json.dumps({'alg':'HS256','typ':'JWT'}).encode()).rstrip(b'=').decode()
payload_data = {'role':'service_role','iss':'supabase','iat':$(date +%s),'exp':$(($(date +%s) + 315360000))}
payload = base64.urlsafe_b64encode(json.dumps(payload_data).encode()).rstrip(b'=').decode()
sig = base64.urlsafe_b64encode(hmac.new('${JWT_SECRET}'.encode(), f'{header}.{payload}'.encode(), hashlib.sha256).digest()).rstrip(b'=').decode()
print(f'{header}.{payload}.{sig}')
" 2>/dev/null || echo "GENERATE_ME")

  cp .env.example .env
  sed -i "s|POSTGRES_PASSWORD=.*|POSTGRES_PASSWORD=${POSTGRES_PASSWORD}|" .env
  sed -i "s|JWT_SECRET=.*|JWT_SECRET=${JWT_SECRET}|" .env
  sed -i "s|ANON_KEY=.*|ANON_KEY=${ANON_KEY}|" .env
  sed -i "s|SERVICE_ROLE_KEY=.*|SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}|" .env
  sed -i "s|REALTIME_DB_PASSWORD=.*|REALTIME_DB_PASSWORD=${POSTGRES_PASSWORD}|" .env

  echo "  Generated secrets and JWT keys."
  echo "  IMPORTANT: Edit .env to set your SITE_DOMAIN before proceeding."
else
  echo "[1/5] .env already exists, skipping generation."
fi

# ── Step 2: Source .env ────────────────────────────────
echo "[2/5] Loading configuration..."
set -a
source .env
set +a

# ── Step 3: Generate runtime config.js for frontend ───
echo "[3/5] Generating frontend config.js..."

# For self-hosted, the frontend talks to the API via the /api/ reverse proxy
SUPABASE_PUBLIC_URL="${SUPABASE_PUBLIC_URL:-http://localhost:8080/api}"

cat > volumes/nginx/config.js <<JSEOF
// Promise Tracker — Runtime Configuration (auto-generated by setup.sh)
window.__PROMISE_TRACKER_CONFIG__ = {
  SUPABASE_URL: '${SUPABASE_PUBLIC_URL}',
  SUPABASE_ANON_KEY: '${ANON_KEY}'
};
JSEOF
echo "  Frontend will connect to: ${SUPABASE_PUBLIC_URL}"

# ── Step 4: Prepare database init scripts ──────────────
echo "[4/5] Preparing database initialization..."
mkdir -p volumes/db/init

# Copy migration and seed files into the DB init directory
# PostgreSQL runs these in alphabetical order on first start
if [ ! -f volumes/db/init/01_roles.sql ]; then
  cat > volumes/db/init/01_roles.sql <<'SQLEOF'
-- Create roles expected by PostgREST and GoTrue
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'anon') THEN
    CREATE ROLE anon NOLOGIN NOINHERIT;
  END IF;
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'authenticated') THEN
    CREATE ROLE authenticated NOLOGIN NOINHERIT;
  END IF;
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'service_role') THEN
    CREATE ROLE service_role NOLOGIN NOINHERIT BYPASSRLS;
  END IF;
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'authenticator') THEN
    CREATE ROLE authenticator NOINHERIT LOGIN;
  END IF;
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'supabase_auth_admin') THEN
    CREATE ROLE supabase_auth_admin NOINHERIT CREATEROLE LOGIN;
  END IF;
END
$$;

-- Grant role memberships
GRANT anon TO authenticator;
GRANT authenticated TO authenticator;
GRANT service_role TO authenticator;
GRANT ALL ON DATABASE promise_tracker TO supabase_auth_admin;

-- Set authenticator password (same as POSTGRES_PASSWORD)
ALTER ROLE authenticator WITH PASSWORD 'POSTGRES_PASSWORD_PLACEHOLDER';
ALTER ROLE supabase_auth_admin WITH PASSWORD 'POSTGRES_PASSWORD_PLACEHOLDER';
SQLEOF

  # Replace placeholder with actual password
  sed -i "s|POSTGRES_PASSWORD_PLACEHOLDER|${POSTGRES_PASSWORD}|g" volumes/db/init/01_roles.sql
fi

# Copy the schema migration
if [ ! -f volumes/db/init/02_schema.sql ]; then
  cp ../supabase/migrations/001_foundation.sql volumes/db/init/02_schema.sql
  echo "  Copied schema migration."
fi

# Copy seed data
if [ ! -f volumes/db/init/03_seed.sql ]; then
  cp ../supabase/seed/002_seed_data.sql volumes/db/init/03_seed.sql
  echo "  Copied seed data."
fi

# Grant permissions to PostgREST roles
if [ ! -f volumes/db/init/04_grants.sql ]; then
  cat > volumes/db/init/04_grants.sql <<'SQLEOF'
-- Grant read access to anon role (public data)
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO anon;
GRANT ALL ON ALL TABLES IN SCHEMA public TO authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO service_role;

-- Allow anon to execute the scoring function
GRANT EXECUTE ON FUNCTION compute_accountability_score(UUID) TO anon, authenticated, service_role;

-- Default privileges for future tables
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO anon;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO authenticated;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO service_role;
SQLEOF
  echo "  Created role grants."
fi

# ── Step 5: Update Kong config with actual keys ────────
echo "[5/5] Configuring API gateway..."
sed "s|\${ANON_KEY}|${ANON_KEY}|g; s|\${SERVICE_ROLE_KEY}|${SERVICE_ROLE_KEY}|g" \
  volumes/kong/kong.yml > volumes/kong/kong.yml.tmp && mv volumes/kong/kong.yml.tmp volumes/kong/kong.yml

# ── Cloud-init auto-configuration ─────────────────────
if [ "${CLOUD_INIT:-}" = "1" ]; then
  echo "[cloud-init] Detecting VM IP address..."
  VM_IP=$(hostname -I | awk '{print $1}')

  # Update .env with the detected IP
  sed -i "s|SITE_DOMAIN=.*|SITE_DOMAIN=${VM_IP}|" .env
  sed -i "s|SUPABASE_PUBLIC_URL=.*|SUPABASE_PUBLIC_URL=http://${VM_IP}:8080/api|" .env
  sed -i "s|GOTRUE_SITE_URL=.*|GOTRUE_SITE_URL=http://${VM_IP}:8080|" .env

  # Re-source .env and regenerate frontend config
  set -a
  source .env
  set +a

  cat > volumes/nginx/config.js <<JSEOF
// Promise Tracker — Runtime Configuration (auto-generated by setup.sh)
window.__PROMISE_TRACKER_CONFIG__ = {
  SUPABASE_URL: 'http://${VM_IP}:8080/api',
  SUPABASE_ANON_KEY: '${ANON_KEY}'
};
JSEOF

  echo "[cloud-init] Configured for IP: ${VM_IP}"
  echo "[cloud-init] Frontend will be at http://${VM_IP}:8080"
else
  echo ""
  echo "============================================"
  echo "  Setup complete!"
  echo "============================================"
  echo ""
  echo "  Next steps:"
  echo "    1. Review/edit .env (especially SITE_DOMAIN)"
  echo "    2. Start the stack:"
  echo "       docker compose up -d"
  echo ""
  echo "  Access points:"
  echo "    Frontend:  http://localhost:8080"
  echo "    API:       http://localhost:8000"
  echo "    Studio:    http://localhost:3000"
  echo ""
  echo "  For production with TLS, put a reverse proxy"
  echo "  (Caddy, Traefik, or Nginx Proxy Manager)"
  echo "  in front on ports 80/443."
  echo ""
fi
