// Promise Tracker — Runtime Configuration
// This file is generated by setup.sh and mounted into the Nginx container.
// Edit the .env file and run ./setup.sh to regenerate.
window.__PROMISE_TRACKER_CONFIG__ = {
  SUPABASE_URL: '%%SUPABASE_PUBLIC_URL%%',
  SUPABASE_ANON_KEY: '%%ANON_KEY%%'
};
